# Generated by Django 5.2.8 on 2026-02-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Facvoritos'},
        ),
    ]
